version: '3'

services:

  kloud_redis:
    image: redis:latest

  kloud_fast_api:
    build: server
    ports:
      - "8000:8000"
    volumes:
      - ./server/app:/app
    depends_on:
      - kloud_redis
      - kloud_celery
    entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 8000

  kloud_celery:
    build: data_analysis
    depends_on:
      - kloud_redis
    entrypoint: celery -A app.da_tasks worker --loglevel=info
